jwt:
  secret: '[a-a-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOthersSymbo$'
  expiration:
    time: 432_000_000
server:
  port: 8081
  shutdown: graceful

spring:
  datasource:
    url: jdbc:h2:./temp
    username: sa
  jpa:
    hibernate:
      ddl-auto: update